import { Link } from "react-router-dom";

const LegalDisclaimer = () => (
  <div className="bg-muted/30 border border-border rounded-xl p-5 mt-8 space-y-4">
    <div>
      <p className="text-xs font-semibold text-foreground mb-1">Important: Not Medical Advice</p>
      <p className="text-xs text-muted-foreground leading-relaxed">
        This report is generated by artificial intelligence for educational and informational purposes only. It does not constitute medical advice, a medical diagnosis, a clinical assessment, or a substitute for consultation with a qualified healthcare professional. Peptyl is not operated by, affiliated with, or supervised by any registered medical professional, genetic counsellor, pharmacist, or other healthcare provider.
      </p>
    </div>

    <div>
      <p className="text-xs font-semibold text-foreground mb-1">Genetic Data &amp; Special Category Processing</p>
      <p className="text-xs text-muted-foreground leading-relaxed">
        Your genetic data is classified as special category data under UK GDPR Article 9 and the Data Protection Act 2018. By uploading your data, you have explicitly consented to it being processed solely to generate this personalised educational report. Your raw genetic data is not stored — only the derived report is retained. You may delete your report at any time from your DNA dashboard. Peptyl is in the process of registering with the UK Information Commissioner's Office (ICO) as a data controller for special category data processing.
      </p>
    </div>

    <div>
      <p className="text-xs font-semibold text-foreground mb-1">AI Limitations</p>
      <p className="text-xs text-muted-foreground leading-relaxed">
        Variant interpretation, supplement suggestions, and health scores are generated by our AI system and have not been validated in clinical settings. AI systems can make errors. Results should not be used to make decisions about medications, medical treatments, or clinical interventions without independent professional review.
      </p>
    </div>

    <div>
      <p className="text-xs font-semibold text-foreground mb-1">Before Acting on This Report</p>
      <ul className="text-xs text-muted-foreground leading-relaxed list-disc pl-4 space-y-1">
        <li>Consult your GP or a registered healthcare professional before changing any medication</li>
        <li>Consult a certified genetic counsellor before drawing clinical conclusions from variant data</li>
        <li>Consult a registered pharmacist before adding or changing supplements</li>
        <li>Do not use this report to self-diagnose or self-treat any health condition</li>
      </ul>
    </div>

    <p className="text-xs text-muted-foreground leading-relaxed pt-2 border-t border-border">
      By viewing this report you confirm you understand and accept these limitations. Full terms:{" "}
      <Link to="/terms-of-service" className="text-primary hover:underline">/terms-of-service</Link>
      {" | "}Privacy &amp; genetic data:{" "}
      <Link to="/privacy-policy" className="text-primary hover:underline">/privacy-policy</Link>
    </p>
  </div>
);

export default LegalDisclaimer;
